name: remote ssh command
on:
  push:
    branches:
      -main

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: http://88.80.189.81/
        username: root
        password: ${{ secrets.LINODE_PASSWORD }}
        port: 22
        script: |
          cd shorturl
          git pull
          docker-compose up -d --build app
